apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
  labels:
    role: {{ .Values.role }}
    version: {{ .Values.version }}
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=