apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    role: {{ .Values.role }}
    version: {{ .Values.version }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
