#Imperative command to create service to expose frontend deployment 
#kubectl expose deploy api \ --name=api \ --type=LoadBalancer \ --port=80 \ --target-port=8080
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/app-instance: {{ .Values.app-instance }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app-instance: {{ .Values.app-instance }}
    version: {{ .Values.version }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
