apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.name}}
spec:
  host: {{ .Values.name}}.{{ .Values.namespace}}.svc.cluster.local
  subsets:
  - name: {{ Values.subset1 }}
    labels:
      version: {{ .Values.version }}
  - name: {{ Values.subset2 }}
    labels:
      version: {{ .Values.version2 }}
      
