apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/app-instance: {{ .Values.app-instance }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    db: {{ .Values.app-instance }}
    version: {{ .Values.version }}